### ISSUE TITLE
有成功run起来的吗？分享下版本和步骤

### ISSUE THREAD

**Issue by feng1990liu** [apchenstu/sofgan#12]

**Comment by Jack12xl** [comment]
hi, 可以试下这个[colab demo](https://colab.research.google.com/drive/1V03JfVsuOamgncWMXoOOSRsQPzd35x5v?usp=sharing)如果发现dependency比较难装

**Comment by 18322233491** [comment]
python3 :
1、git clone https://github.com/apchenstu/sofgan.git --recursive
2、pip install -r ./Painter/requirements.txt
3、python ./Painter/run_UI.py

**Comment by CangHaiQingYue** [comment]
@feng1990liu 大佬跑起来了，我按照@18322233491的步骤，只有IU，但是右边没有生成相应的图像。
