### ISSUE TITLE
about --load_network error 

### ISSUE THREAD

**Issue by zhanghongyong123456** [apchenstu/sofgan#15]
windows10 cuda 11.1 pytorch1.8.2 python 3.8
![image](https://user-images.githubusercontent.com/48466610/130888524-36a60995-e853-468d-9c5c-20057047e381.png)
![image](https://user-images.githubusercontent.com/48466610/130888557-14e50063-98dd-4d6e-a044-96de062ecd5b.png)

**Comment by apchenstu** [comment]
I haven't tested the code on the Windows platform. You can try `pytorch==1.7.1 torchvision==0.8.2`, if the err is still here, I think you may need to switch to ubuntu.

**Comment by zhanghongyong123456** [comment]
> I haven't tested the code on the Windows platform. You can try `pytorch==1.7.1 torchvision==0.8.2`, if the err is still here, I think you may need to switch to ubuntu.

ok，thank you very much for your prompt reply
