### ISSUE TITLE
Can you release the code of the tool of generate segmap

### ISSUE THREAD

**Issue by kinglon** [apchenstu/sofgan#17]
I can download your pre-process ffhq and celeba segmaps, but can't find the tool's code, can you release its code or the tool?
Now , I want to train the model for anime, and need to generate anime's segmap for train.

**Comment by apchenstu** [comment]
please refer to this [repo](https://github.com/zllrunning/face-parsing.PyTorch)

**Comment by kinglon** [comment]
Thanks very much.

**Comment by zhouwy19** [comment]
What are the attributes of these labels?
