### ISSUE TITLE
Why do the Generator not use the real images in train.py

### ISSUE THREAD

**Issue by kinglon** [apchenstu/sofgan#18]
I looked through the train.py, and didn't find the Generator use the real image.
I doubt if the Generator load a pre-train model that have learned from a lot of real images.
Now, I want to use sofgan to generate an anime photo, can I achieve it after a model train only using the real anime pictures and its segmaps.

**Comment by apchenstu** [comment]
sorry, I could not catch the question, could you ask it in another way?

**Comment by kinglon** [comment]
I have learnt the answer from [this article](https://towardsdatascience.com/mangagan-8362f06b9625).
The Discriminator learns features from real image, then tell the Generator those features.
The Generator uses those features to generate fake images.
