### ISSUE TITLE
About the anime face parsing.

### ISSUE THREAD

**Issue by kingofprank** [apchenstu/sofgan#2]
Hello! Thanks for you amazing work. I am very interesting about your job. I am studying on some anime projects, on the project homepage(https://apchenstu.github.io/sofgan/), I saw that you show the editing effect of an animation (Video 5b: Generation from drawing). Where did the animation parsing data you use come from? Can you share the anime data link?

**Comment by Jack12xl** [comment]
Hi, the anime data link is from [deemos](https://www.deemos.com). Sry we could not share the anime data for now
