### ISSUE TITLE
Your pre-process ffhq and celeba segmaps zip file contain duplicate files

### ISSUE THREAD

**Issue by Jianhua-Cui** [apchenstu/sofgan#22]
Hi, thank you for your amazing work!
I found an error in the zip file you provided : "segmaps.zip" from https://drive.google.com/file/d/1_gSENMI5hYj-JTjqtn14PkoLLnEp94oY/view?usp=sharing
This zip file contains two directories : "FFHQ" and "CelebAMask-HQ". However, these two directories contain totally duplicate files. It seems that the directory "CelebAMask-HQ" contains wrong content.
Could you please provide the pre-processed segmaps for CelebAMask-HQ?

**Comment by Jianhua-Cui** [comment]
I write my own code to generate segmaps substitute for this Celebamask-HQ dataset. 
The link is : https://drive.google.com/file/d/1iFIbqo_cU558oY2fEVb-iFXLLtSFW1JX/view?usp=sharing
Note that CelebAMask-HQ does not contain "l_nose" and "r_nose" categories, but only one "nose" category. So I set the index of the "nose" category to 6, the same as "r_nose" in FFHQ.
If anyone uses these segmaps, I'm very glad to be pointed out.

**Comment by apchenstu** [comment]
updated it, thanks for pointing it out!
