### ISSUE TITLE
Can you release the code of inversing the real images

### ISSUE THREAD

**Issue by Samaritan-Infi** [apchenstu/sofgan#9]
Impressed by your elegant work!
Can you release the code of inversing the real images; That will be a great help!

**Comment by apchenstu** [comment]
Hi thanks, the inverse code is include in the "projector.py"

**Comment by LiUzHiAn** [comment]
Hi, could you please tell the difference between the `model_seg_input` and `model_seg_input2`? Since the `modules.model_seg_input2` cannot be found in `projector.py`. Thx.
